### ISSUE TITLE
www.ifon.ca

### ISSUE THREAD

**Issue by 3-2** [easylist/easylist#12427]
### List the website(s) you're having issues:
```
https://www.ifon.ca/
```

### What happens?
The page gets blurred and I can't scroll.
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/25643218/176429936-fa28d276-846d-429b-9225-21780a83ff20.png">

### List Subscriptions you're using:
EasyList
Adblock Warning Removal List

### Your settings
No other extensions.

- OS/version: macOS Monterey 12.4
- Browser/version: Chrome 103.0.5060.53
- Adblock Extension/version: Adblock Plus 3.14

**Comment by yokoffing** [comment]
Looks like a `Adblock Warning Removal List` issue.

**Comment by krystian3w** [comment]
@smed79 / @dimisa-ruadlist

**Comment by krystian3w** [comment]
For home users both are accepted, AWRL no cover this page due Eyeo?

**Comment by dimisa-RUAdList** [comment]
Snippets in Adblock Plus only work when they are placed in [ABP filters](https://github.com/abp-filters). However, this particular snippet `ifon.ca#$#abort-on-property-read tie.ad_blocker_detector` cannot be placed there due to legal restrictions.

As for the solution to the problem in the AWRL, there is simply no section for Canada: https://github.com/easylist/antiadblockfilters/tree/master/antiadblockfilters

I don't know who should solve this problem.

@ryanbr

**Comment by krystian3w** [comment]
Maybe user to change ABP to uBO, stock config no generate alarm. I no checked AdGuard, maybe repair page long time ago.

**Comment by 3-2** [comment]
@Khrin @dimisa-RUAdList @krystian3w 
So the reason why this issue is still not solved (or, is invalid? ) is that there is no place to put filter snippets?
I don't know much about your operational mechanism since I'm just a user.

**Comment by krystian3w** [comment]
Spinnets is limited to ad-reinsertion/pop-ups in Anti-CV repo: https://github.com/abp-filters/abp-filters-anti-cv

If no possible add page to English section in ARWL then you must start write own list for Adblock Plus by github/gitlab repo.
