### ISSUE TITLE
Including p.typekit.net in filter list is creating errors on applications

### ISSUE THREAD

**Issue by RomanFausek** [easylist/easylist#14723]
Hello!

Can I ask you why are you blacklisting `p.typekit.net`? I saw it being added in this commit https://github.com/easylist/easylist/commit/22a3441fe31e5a5be6d1307026961afe0b2a2b7c

The file from `p.typekit.net` with just the comment inside gets thrown away with assets (fonts) from the network which leads to font fallback in our application. The issue is that for some security policies, once it gets ignored, the rest of the request is thrown away.

In the following screens, you can see that downloading the file from `p.typekit.net` allows the network to continue downloading assets. But the screen with the ad block throws away the rest of the promise (which are the actual font assets).
![Screenshot 2023-01-19 at 10 53 03](https://user-images.githubusercontent.com/8074997/213418534-277a1c5e-8806-401d-a2ee-3951ad8c1836.png)
![Screenshot 2023-01-19 at 10 50 56](https://user-images.githubusercontent.com/8074997/213418558-02a419c9-43df-43a6-b863-8dfdce847a2e.png)

It is apparently not just us because I found out that at uBlock they are already adding whitelisted URLs and this whitelisting approach doesn't make sense to me at all https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt#L4865. I understand that you are afraid of some trackers but it might create problems for many websites using ad blocks with your filter list.

Some more details + conversation is here https://github.com/uBlockOrigin/uAssets/issues/16391

**Comment by garry-ut99** [comment]
> RomanFausek : but it might create problems for many websites using ad blocks with your filter list.

https://publicwww.com/websites/%22p.typekit.net%22/

**Comment by ryanbr** [comment]
See details on https://github.com/easylist/easylist/pull/14679

**Comment by RomanFausek** [comment]
@ryanbr This needs a resolution (possibly a revert of #14679) and not just a link to the PR. So I don't agree that it is resolved.

Typekit is a commonly used service and including it in your list makes it unusable for many websites. Many of our customers are already reporting it. The only solution right now is not to use ad block extensions.

**Comment by garry-ut99** [comment]
> stephenhawk8054 : https://github.com/uBlockOrigin/uAssets/issues/16391#issuecomment-1396728719 : `p.typekit.net` I'm not sure about its privacy history. Looks like it's related to Adobe's trackers?

Seems so, because visiting it redirects to https://fonts.adobe.com/ (and visiting `primer.typekit.net` as well)

Also there are more `typekit.net` filters: 
- `||p.typekit.net^` in Polish Privacy Filters: [LINK](https://github.com/olegwukr/polish-privacy-filters/blob/6c27ad281626b7d486979e5edc98290679e7412e/adblock.txt#L27)
- `||primer.typekit.net^$xmlhttprequest` in EasyPrivacy: [LINK](https://github.com/easylist/easylist/blob/b2e06079de5ae84461bd2a9620941d4a759e11ec/easyprivacy/easyprivacy_thirdparty.txt#L1486)
- `||primer.typekit.net^$xmlhttprequest` in AdGuard Tracking Protection: [LINK](https://github.com/AdguardTeam/AdguardFilters/blob/d9b89bd82e4f34aa86ec6b216063feba0ae520c1/SpywareFilter/sections/specific.txt#L857)
- `||ping.typekit.net/p.gif` in AdGuard Tracking Protection: [LINK](https://github.com/AdguardTeam/AdguardFilters/blob/d9b89bd82e4f34aa86ec6b216063feba0ae520c1/SpywareFilter/sections/specific.txt#L3013)

As for `||primer.typekit.net^$xmlhttprequest` in EasyPrivacy, initially it was `||primer.typekit.net^` but it has been changed to `||primer.typekit.net^$xmlhttprequest` due to some breakages reported in:
- https://github.com/easylist/easylist/issues/10176
- https://github.com/uBlockOrigin/uAssets/issues/10998 

Also two other breakages caused by blocking `typekit.net` in AdGuard Tracking Protection:
- https://github.com/AdguardTeam/AdguardFilters/issues/55288

**Comment by AdrienPoupa** [comment]
Hello, users from [RSI](https://robertsspaceindustries.com) have reported this as breaking a whole section of the website: https://robertsspaceindustries.com/spectrum/community/SC/forum/5/thread/pledge-store-broken-in-firefox

We are using the following CSS snippet: https://robertsspaceindustries.com/pledge-store/index.0255427d690534770b84.css
```css
@import url(https://use.typekit.net/zpw1qvn.css);
```
Then, https://use.typekit.net/zpw1qvn.css loads the following:
```css
@import url("https://p.typekit.net/p.css?s=1&k=zpw1qvn&ht=tk&f=28771.28775.28778.28779&a=86281447&app=typekit&e=css");
```
Since `p.typekit.net` is blocked, I guess the previous CSS are not loaded, and the main CSS file is blocked. Given it is a chunk, it prevents all other chunks from loading and the whole website breaks: https://robertsspaceindustries.com/store/pledge/browse/extras/?search=&sort=weight&direction=desc
![image](https://user-images.githubusercontent.com/15086425/214121157-3ac94e60-5c98-403b-9c8a-fcf11d8ac6fe.png)
I strongly feel like the rule should be removed.

**Comment by 0o5rlubm** [comment]
Hello, I'm the one who submitted this block because everything seems to show that this site is a tracker. Indeed, I have not blocked any typekit, but only the p-domain, which serves only empty files, while the needed resources on the other hand are not blocked. 

I would like to apologize for any inconvenience this may have caused.

However, it seems to me that this rule did not impact the millions of sites that use the tool, but only a small handful. In balance between generalized tracking and a few broken sites, easylist owner has chosen to block by default and whitelist the sites that are problematic.

So, please open issues for broken sites, we'll be happy to add them to the whitelist (or directly open a PR like #14775).

**Comment by krystian3w** [comment]
I guess he tested on localhost, so maybe needed add:

```adb
*$                   ,domain=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local
```

or AdGuard idea to "My filters" panel (due files still don't support supplements for uBo and Eyeo blocked copy these files to own mirrors):
```adb
||p.typekit.net^$stylesheet,removeparam
```
